# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "9692c1e4f61ee2f31cef51461ec44698"
name = "testing-cli"
handle = "testing-cli-10"
application_url = "https://signatures-delays-jun-devices.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "google-sopping-ads.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://signatures-delays-jun-devices.trycloudflare.com/auth/callback",
  "https://signatures-delays-jun-devices.trycloudflare.com/auth/shopify/callback",
  "https://signatures-delays-jun-devices.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks"

[pos]
embedded = false
